packages/webgal/src/Core/gameScripts/intro.tsx
修复了点击全屏文字时无法前进到下一条语句的问题。
全画面テキストをクリックしても次のステートメントに進まない問題を修正しました。
Fixed a problem where clicking full-screen text could not advance to the next statement.
=> Fixed an issue with full-screen text

packages/webgal/src/Components/Stage/Stage.tsx, packages/webgal/src/Core/gameScripts/playVideo.tsx
@MakinoharaShoko 
https://github.com/MakinoharaShoko/WebGAL_Terre/issues/170
**Audio Volume Reference:** The audio volume for videos now references the volume set for the BGM. 
**Menu Visibility during Playback:** The menu is now hidden while a video is playing. 
**Non-Skippable by Single Click:** Previously, a single click would skip the video. This behavior has been changed. 
**Skip via Double Click:** If users wish to skip the video, they can do so by double-clicking.
=> Video Playback, Volume Control, and User Interface Adjustments.

packages/webgal/src/Stage/Stage.tsx
=> feat: New logic for controls visibility

packages/webgal/src/Core/controller/gamePlay/scriptExecutor.ts, packages/webgal/src/Core/gameScripts/choose/choose.module.scss, packages/webgal/src/Core/gameScripts/choose/index.tsx
=> feat: choose option supports conditions

packages/webgal/src/Core/gameScripts/setVar.ts
修复了当setVar访问`config.txt`的内容时，字符串会出现编译错误的问题
=> fix:修复setVar进行compile字符串时异常

packages/webgal/src/Core/controller/gamePlay/scriptExecutor.ts, packages/webgal/src/Core/gameScripts/setVar.ts
resolve #528 
resolve #527 
以及实现:
> setVar:emptyText=; 预期赋值为空字符创
鉴于多处对于`getValueFromState`取不到都需要处理，统一包成`getValueFromStateElseKey`。
测试用例：
```
setVar:zero=0;
setVar:emptyText=;
Tester:absent var shows as {absent}, zero var shows as {zero}, empty text var shows as {emptyText}.
setVar:ref_absent=absent;
setVar:ref_zero=zero;
setVar:ref_emptyText=emptyText;
Tester:ref_absent var shows as {ref_absent}, ref_zero var shows as {ref_zero}, ref_empty text var shows as {ref_emptyText}.
setVar:computed=zero + zero;
Tester:computed zero var shows as {computed}
```
=> fix: var value handle

packages/webgal/src/Stage/TextBox/IMSSTextbox.tsx, packages/webgal/src/Stage/TextBox/TextBox.tsx, packages/webgal/src/Stage/TextBox/legacy-themes/legacy-standard/StandardTextbox.tsx, packages/webgal/src/Stage/TextBox/types.ts, packages/webgal/src/UI/Backlog/Backlog.tsx, packages/webgal/src/UI/Menu/Options/TextPreview/TextPreview.tsx
1.修改了showName类型以及相关引用
2.由于脚本中的第一个':'会被认为是角色名称与对话文本的分割，因此在对角色名称使用拓展文本语法时需要将‘:’替换为'~'，再由代码对其进行替换
=> feat:使得文本拓展语法对角色名称生效

packages/webgal/src/Core/gameScripts/say.ts
Related to #539
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/OpenWebGAL/WebGAL/issues/539?shareId=2f2b38a0-2d13-4d96-a0c8-1c76c53c092c).
=> Fix say script to replace spaces with \u00a0

packages/parser/src/index.ts, packages/parser/src/sceneTextPreProcessor.ts, packages/parser/test/parser.test.ts, packages/parser/test/parserMultiline.test.ts
This PR enhances #558 with new features and tests.
In short, the preprocessor now does not consider any lines with `-concat` as a new line. This prevents the ambiguity of statements like
```
aaa 
|bbb -concat
```
being preprocessed as one line 
```
aaa|bbb -concat
;_WEBGAL_LINE_BREAK_|bbb -concat
```
but breaks the original grammar of "show `aaa` at the first line, then show `bbb` at the second line when user clicks".
---
Now, the preprocessor will not handle this, only outputting
```
aaa 
|bbb -concat
```
---
The user can forcely enable multiline support in such case by adding `\` to the end of the first line, i.e., 
```
aaa\
|bbb -concat
```
which will be preprocessed as 
```
aaa|bbb -concat
;_WEBGAL_LINE_BREAK_|bbb -concat
```
=> Process line break: force-multiline & tests

.github/workflows/deploy-demo-page.yml, .github/workflows/pr-check.yml, package.json
Updated GitHub Actions workflows to use node version from package.json.
- Modified GitHub Actions workflows to dynamically use Node.js version from package.json
- Added explicit Node.js engine specification in package.json
In `.github/workflows/deploy-demo-page.yml`:
- Changed `node-version: 16` to `node-version-file: package.json`
In `.github/workflows/pr-check.yml`:
- Similar workflow configuration updates as in deploy-demo-page workflow
In `package.json`:
- Added `engines` field to specify Node.js version
=> feat(ci): Retrieve the Node.js version from package.json

packages/webgal/src/config/language.ts
针对 Issue #600
根据反馈，将语言选项中的“中文”更新为“简体中文”，以减少繁体中文用户的混淆，并提升用户体验。
=> feat: Rename "中文" to "简体中文" for better clarity

packages/webgal/src/Core/gameScripts/setVar.ts
为 `random` 提供了参数选项，与lodash相同的参数：
```
random();
// => a floating-point number
random(0, 5);
// => an integer between 0 and 5
random(5);
// => also an integer between 0 and 5
random(5, true);
// => a floating-point number between 0 and 5
random(1.2, 5.2);
// => a floating-point number between 1.2 and 5.2
```
issue : #654
=> feat: support random function range arguments

packages/webgal/src/UI/Menu/Options/TextPreview/TextPreview.tsx
此 PR 为文本预览组件增加了点击强制刷新功能，用户现在可以通过点击预览区域强制刷新文本预览，提升用户在调整文字显示参数时的反馈体验。
resolve #621
=> feat(text-preview): add click interaction to force refresh preview

packages/webgal/src/Core/controller/stage/pixi/PixiController.ts, packages/webgal/src/Core/controller/stage/pixi/spine.ts
修复宽高比宽于画布的立绘的初始定位问题，应该能 close #685 
新建一个测试工程，下载这两张图片到Figure目录里
<table>
<tr>
<td align="center">宽于16比9.png</td>
<td align="center">宽于16比9.png</td>
</tr>
<tr>
<td align="center"><img src="https://github.com/user-attachments/assets/0deaee20-9b95-44d5-b569-662061637f6d" width="100%"/></td>
<td align="center"><img src="https://github.com/user-attachments/assets/d38d9ac9-4254-4820-8bb3-d899133a539f" width="100%"/></td>
</tr>
</table>
新建一个txt，并粘贴如下代码
```js
changeFigure: 宽于16比9.png -transform={"alpha":0.5} -id=aaa -next;
changeFigure: 窄于16比9.png -transform={"alpha":0.5} -id=bbb -next;
:;
```
应当能看到以下区别
<table>
<tr>
<td align="center">Before</td>
<td align="center">After</td>
</tr>
<tr>
<td align="center"><img src="https://github.com/user-attachments/assets/3e32a791-9b65-4f8f-9678-040048d58461" …
=> fix: figure initial position

packages/webgal/src/UI/Title/Title.tsx, packages/webgal/src/translations/de.ts, packages/webgal/src/translations/en.ts, packages/webgal/src/translations/fr.ts, packages/webgal/src/translations/jp.ts, packages/webgal/src/translations/zh-cn.ts, packages/webgal/src/translations/zh-tw.ts
此pr 添加了退出游戏的按钮，在网页上使用`window.close`，将会关闭当前游戏标签页。
在electron中，结合[feat: add close event ](https://github.com/OpenWebGAL/WebGAL_Terre/pull/410)  此PR可实现在桌面端关闭游戏。
=> feat: add exit button

packages/webgal/src/Core/Modules/animationFunctions.ts, packages/webgal/src/Core/Modules/animations.ts, packages/webgal/src/Core/controller/stage/pixi/animations/generateTransformAnimationObj.ts, packages/webgal/src/Core/controller/stage/pixi/animations/timeline.ts, packages/webgal/src/Core/gameScripts/changeBg/index.ts, packages/webgal/src/Core/gameScripts/changeFigure.ts, packages/webgal/src/Core/gameScripts/setAnimation.ts, packages/webgal/src/Core/gameScripts/setTempAnimation.ts, packages/webgal/src/Core/gameScripts/setTransform.ts
- 为 `changeFigure` `changeBg` `setTransform` 添加 __缓动__ 参数
- 语法: `-ease=easeType` 其中 `easeType` 可为
- `linear`
- `anticipate`
- `easeIn`
- `easeOut`
- `easeInOut` (默认值)
- `circIn`
- `circOut`
- `circInOut`
- `backIn`
- `backOut`
- `backInOut`
- `bounceIn`
- `bounceOut`
- `bounceInOut`
- 用户可以在自定义 animation 里添加 `ease: string` 属性, 例如:
```json
[
{
"scale": {
"x": 1,
"y": 1
},
"duration": 0
},
{
"scale": {
"x": 1.15,
"y": 1.15
},
"duration": 2000,
"ease": "easeOut"
},
{
"scale": {
"x": 1,
"y": 1
},
"duration": 2000,
"ease": "linear"
}
]
```
close #643 
为 `setTransform` `setAnimation` `setTempAnimation` 添加 __写入默认值__ 参数
语法: `-writeDefault` `-writeDefault=true` `-writeDefault=false`
当值为 `true` 时, 没有填写的 ITransform 属性会从 baseTransform 找值
当值为 `false` 时, 没有填写的 ITransform 属性会继承当前 ITransform 的终值
注意: …
=> feat: add ease and write default argument

packages/webgal/src/Core/controller/stage/pixi/WebGALPixiContainer.ts, packages/webgal/src/Core/controller/stage/pixi/shaders/BevelFilter.ts, packages/webgal/src/store/stageInterface.ts
改进了倒角滤镜
<table>
<tr>
<td align="center">Before</td>
<td align="center">After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
- 新增自定义 BevelFilter
- 倒角的亮部混合模式更改为 __滤色__ , 暗部更改为 __正片叠底__
- 修复半透明立绘应用倒角时, 颜色被压暗的问题
- 新增 `bevelSoftness` 属性, 范围 0~1, 控制倒角软化程度
```js
changeBg:bg.png -next;
changeFigure:stand.png -id=aaa;
setTransform:{"brightness":0.1,"contrast":1.5,"saturation":0.8,"gamma":0.8,"bloom":1,"bloomBrightness":1,"bloomBlur":10} -target=bg-main -duration=2000 -next;
setTransform:{"brightness":0.5,"bloom":1,"bloomBlur":10,"bloomThreshold":0.6,"bevel":0.8,"bevelSoftness":1,"bevelRed":85,"bevelGreen":205,"bevelThickness":20,"bevelRotation":60} -target=aaa -duration=2000;
```
=> feat: improve bevel filter

packages/webgal/src/Core/gameScripts/intro.tsx
支持在intro中使用背景图片，图片不存在则会使用backgroundColor
缺少background图片则会兼容backgroundColor
1. 图片尝试顺序：webp->png->jpg
2. 默认intro背景图片路径：game\template\Intro\bg.png (or webp, jpg)
=> feat: allow backgroundImage for Intro, fail to fetch image will fallback to backgroundColor

packages/webgal/src/Core/gameScripts/changeFigure.ts, packages/webgal/src/Stage/MainStage/useSetFigure.ts
立绘可以在任何 `changeFigure` 语句中设置 `zIndex`, 不只限于出场
值小于 0 或不设置 zIndex, zIndex不会变化
```js
changeBg: bg.png;
;
label: loop;
;
changeFigure:1/open_eyes.png -id=aaa -transform={"position":{"x":300}} -next -zIndex=0;
changeFigure:2/open_eyes.png -id=bbb -transform={"position":{"x":-300}} -next -zIndex=1;
: 左 1 右 0;
;
changeFigure:1/open_eyes.png -id=aaa -next -zIndex=1;
changeFigure:2/open_eyes.png -id=bbb -next -zIndex=0;
: 左 0 右 1;
;
jumpLabel: loop;
```
=> feat: apply z index when it changes

packages/webgal/index.html, packages/webgal/public/lib/index.js
- 修改了`index.html`文件中的`loadScript`部分
- 将`index.html`文件中导入第三方插件的代码移动到了`public/lib/index.js`文件中
- 分离项目代码与第三方插件
- 游戏开发者可以通过以下方式向项目中添加IIFE插件而不需要改动项目主体部分的代码
- - 修改`public/lib/index.js`文件中的内容
- - 修改`public/lib/index.js`文件的同时向`public/lib/`文件夹下添加新文件
- `public/lib/index.js`文件中保留了原有的导入第三方插件的逻辑，游戏开发者不需要更改以前的操作方式（将插件文件放在`public/lib/`目录下）
=> refactor: move loadScript to lib/index.js

packages/webgal/src/Core/controller/stage/pixi/PixiController.ts, packages/webgal/src/Core/live2DCore.ts, packages/webgal/src/Core/util/coreInitialFunction/infoFetcher.ts
将初始化 Live 2D 的函数放在 PixiStage 的构造函数中
支持设置旧版表情混合回退
=> fix: initialize live2d in PixiStage constructor

packages/webgal/src/Core/gameScripts/say.ts
修复模拟语音延迟永远为 true 的问题。源于 #739 意外把 center 参数移除，并将 center 作为默认值
=> fix: resume center argument in say command
