.husky/commit-msg
commitlint.config.js
package-lock.json
package.json

给项目添加commitlint规范，参考文档：https://commitlint.js.org/#/

Commitlint

---

public/game/config.txt
public/game/scene/start.txt
src/App.css
src/App.js
src/assets/css/AlertDialog.css
src/assets/css/SettingsScreen.css
src/assets/css/TextBox.css
src/component/ScreenComponent/SettingsScreen.js
src/component/ScreenComponent/TextBox.js
src/component/ScreenComponent/TitleScreen.js
src/core/Config.js
src/core/GamePlay.js
src/utils/KeyShortcut.js

调整了了css的细节表现，
修改了文字框隐藏时的点击逻辑，
创建全局可用Config对象，重构提取config.txt的代码，
同步了滚轮控制的代码，wheel事件中使用ev.preventDefault()会导致报错，因此注释掉了

修复ui交互的错误逻辑，重构提取config.txt的代码，同步滚轮控制的代码

---

src/Components/UI/etc.js
src/Core/StoreControl/StoreControl.js

提取fontSize和playSpeed的默认值至SettingsMap，使用map简化数据获取的方式

提取Settings的默认值，简化if-else的代码

---

index.html
src/Core/util/infoFetcher.ts

用promise改写了一下，只有用户点击过触发enter+渲染完成两个条件同时满足才会响起bgm，挂载的属性用完即删，应该不会造成负面影响

enter后触发bgm

---

src/Components/UI/BottomControlPanel/ButtomControlPanel.tsx
src/Core/controller/gamePlay/fastSkip.ts
src/hooks/useSkip.ts

feat: Support for using CTRL to control fast forward mode

---

src/hooks/useHotkey.tsx

feat: support hot key: enter and space

---

packages/webgal/src/store/userDataReducer.ts

Optimized Packaging

---

packages/webgal/index.html
packages/webgal/src/App.tsx
packages/webgal/src/Components/UI/PanicOverlay/PanicImage/PanicImage.tsx
packages/webgal/src/Components/UI/PanicOverlay/PanicOverlay.tsx
packages/webgal/src/Components/UI/PanicOverlay/PanicYoozle/PanicYoozle.tsx
packages/webgal/src/Components/UI/PanicOverlay/PanicYoozle/panicYoozle.module.scss
packages/webgal/src/Components/UI/PanicOverlay/panicOverlay.module.scss
packages/webgal/src/hooks/useHotkey.tsx
packages/webgal/src/store/GUIReducer.ts
packages/webgal/src/store/guiInterface.ts

Restore the panic screen

---

packages/webgal/src/Components/Stage/TextBox/TextBox.tsx
packages/webgal/src/Components/UI/Backlog/Backlog.tsx

Added newline processing in textbox

Added newline handling

---

packages/webgal/src/Components/Stage/introContainer/introContainer.module.scss
packages/webgal/src/Core/gameScripts/intro.tsx

*fontSize
*backgroundColor
*fontColor

add founction

---

packages/webgal/public/game/scene/demo_ja.txt
packages/webgal/public/game/scene/demo_zh_cn.txt
packages/webgal/src/Components/Stage/AudioContainer/AudioContainer.tsx
packages/webgal/src/Components/UI/Menu/Options/Sound/Sound.tsx
packages/webgal/src/Core/controller/stage/playBgm.ts
packages/webgal/src/Core/controller/stage/setVolume.ts
packages/webgal/src/Core/gameScripts/bgm.ts
packages/webgal/src/Core/initializeScript.ts
packages/webgal/src/store/stageInterface.ts
packages/webgal/src/store/stageReducer.ts

在BGM中添加音量调整功能。
BGMに音量調整機能を追加しました。
Added volume adjustment function to BGM.
The following is one of the available statements. ↓
```
bgm:s_Title.mp3 -volume=80 -enter=3000; // work when volume >= 0 and volume <= 100 
```

Added volume adjustment function to BGM.

---

packages/webgal/src/Components/Stage/AudioContainer/AudioContainer.tsx
packages/webgal/src/Core/gameScripts/playVocal.ts
packages/webgal/src/Core/gameScripts/say.ts
packages/webgal/src/store/stageInterface.ts
packages/webgal/src/store/stageReducer.ts

在Vocal中添加音量调整功能。
Vocalに音量調整機能を追加しました。
Added volume adjustment function to Vocal.
The following is one of the available statements. ↓
```
WebGAL:欢迎使用 WebGAL！这是一款全新的网页端视觉小说引擎。 -v1.wav -volume=10; // work when volume >= 0 and volume <= 100 
```

Added volume adjustment function to Vocal.

---

packages/webgal/src/Components/Stage/TextBox/TextBox.tsx
packages/webgal/src/Core/gameScripts/say.ts
packages/webgal/src/store/stageInterface.ts
packages/webgal/src/store/stageReducer.ts

TextBox_TextSize_Change

---

packages/webgal/src/Components/Stage/AudioContainer/AudioContainer.tsx
packages/webgal/src/Core/gameScripts/bgm.ts
packages/webgal/src/Core/gameScripts/playEffect.ts
packages/webgal/src/Core/gameScripts/playVocal.ts
packages/webgal/src/assets/se/license.txt
packages/webgal/src/store/stageInterface.ts
packages/webgal/src/store/stageReducer.ts

①为 'playEffect' 追加了音量调节功能。
②改进了原有的音量调节功能的代码。
①「playEffect」に音量調整機能を追加しました。
②元の音量調整機能のコードを改善しました。
①Added volume adjustment function to 'playEffect'.
②Improved the code for the original volume adjustment function.
The following is one of the available statements. ↓
```
playEffect:v1.wav -volume=10; // Work when volume >= 0 and volume <= 100 
```

Added volume adjustment function to 'playEffect'.

---

packages/webgal/src/Components/Stage/AudioContainer/AudioContainer.tsx
packages/webgal/src/store/userDataReducer.ts

An error occurred because the value being set to the volume property of HTMLMediaElement exceeded the allowable range (between 0 and 1).
Fixed.

Se_bug_fix

---

packages/webgal/src/Components/Stage/FullScreenPerform/fullScreenPerform.module.scss
packages/webgal/src/Core/gameScripts/intro.tsx

Details are listed below
https://github.com/MakinoharaShoko/WebGAL/issues/348

Added animation for Full Screen Text and added to delay time

---

packages/webgal/src/Components/UI/Extra/ExtraBgm.tsx

Fixed the page crash issue when clicking on the BGM in the Extra page.

Fixed ExtraBgm.tsx

---

packages/webgal/src/Core/gameScripts/bgm.ts
packages/webgal/src/Core/gameScripts/changeBg.ts

Click here for details
https://github.com/MakinoharaShoko/WebGAL/issues/341

unlock function add

---

packages/webgal/src/Core/gameScripts/choose.tsx
packages/webgal/src/hooks/useSoundEffect.ts

Fixed: A bug where the engine would crash when the choose component called the UI sound effect hook.

Fixed: A bug about 'choose' component and UI SE.

---

packages/webgal/public/game/scene/demo_var.txt
packages/webgal/public/game/scene/demo_zh_cn.txt
packages/webgal/public/game/scene/start.txt
packages/webgal/src/Core/controller/gamePlay/scriptExecutor.ts

Made it possible to use `variables` for `speaker` in say statements.
```
setVar:t=Tom;
setVar:s=Sam;
t:It's not Sam, it's Tom.
s:It's not Tom, it's Sam.
```

Made it possible to use variables for `speaker` in `say` statements.

---

README.md
README_EN.md
README_FR.md
README_JP.md
README_KO.md
packages/webgal/src/Stage/Stage.tsx
packages/webgal/src/UI/BottomControlPanel/BottomControlPanel.tsx
packages/webgal/src/UI/GlobalDialog/GlobalDialog.tsx
packages/webgal/src/store/GUIReducer.ts
packages/webgal/src/store/guiInterface.ts

Currently, the "Hide" button hides the whole text box.
However, hiding just controls (bottom buttons) can make a more immersive auto-play mode.
I implemented this by getting current mouse position and computing whether the mouse is in the text box, which decides the controls being shown or not.
(Listening OnMouseLeave event on text box does not work because FullScreenClick is above it)
The user can click the most right "Lock/Unlock" button to trigger this function.

Feature: Hide controls (bottom buttons) when mouse out of text box

---

packages/webgal/src/Core/gameScripts/changeFigure.ts

The function call with corrected parameters.

fix: The function call with corrected parameter

---

packages/webgal/src/Stage/TextBox/TextBox.tsx
packages/webgal/src/Stage/TextBox/themes/imss/IMSSTextbox.tsx
packages/webgal/src/Stage/TextBox/themes/imss/imss.module.scss
packages/webgal/src/Stage/TextBox/themes/standard/StandardTextbox.tsx
packages/webgal/src/Stage/TextBox/themes/standard/standard.module.scss
packages/webgal/src/UI/Menu/Options/Display/Display.tsx
packages/webgal/src/UI/Menu/Options/NormalOption.tsx
packages/webgal/src/UI/Menu/Options/TextPreview/TextPreview.tsx
packages/webgal/src/UI/Menu/Options/TextPreview/textPreview.module.scss
packages/webgal/src/UI/Menu/Options/normalOption.module.scss
packages/webgal/src/UI/Menu/Options/options.module.scss
packages/webgal/src/store/userDataInterface.ts
packages/webgal/src/store/userDataReducer.ts
packages/webgal/src/translations/de.ts
packages/webgal/src/translations/en.ts
packages/webgal/src/translations/fr.ts
packages/webgal/src/translations/jp.ts
packages/webgal/src/translations/zh-cn.ts
packages/webgal/src/translations/zh-tw.ts

feat: can change the opacity of the textbox

---

packages/webgal/src/App.tsx
packages/webgal/src/UI/Menu/Options/Display/Display.tsx
packages/webgal/src/UI/Title/Title.tsx
packages/webgal/src/hooks/useFullScreen.ts
packages/webgal/src/hooks/useHotkey.tsx
packages/webgal/src/main.tsx
packages/webgal/src/store/userDataInterface.ts
packages/webgal/src/store/userDataReducer.ts
packages/webgal/src/translations/en.ts
packages/webgal/src/translations/zh-cn.ts

添加选项以进入游戏时自动全屏。
由于浏览器限制，浏览器上全屏时按 `Esc` 优先退出全屏，全屏时可以用 `Escape` 即 `~` 开启紧急回避。

feat: auto full screen after entering game

---

packages/webgal/src/Core/util/prefetcher/assetsPrefetcher.ts

用 includes 判断 url 是否已经加载，减少不必要的循环。

perf: use "includes" instead of "forEach".

---

packages/webgal/src/Core/controller/stage/pixi/PixiController.ts
packages/webgal/src/Stage/TextBox/IMSSTextbox.tsx

原写法,每一帧动画都添加一个精灵模型,导致卡顿
https://pixijs.com/8.x/examples/sprite/texture-swap

perf: 🎈 use texture swap

---

packages/webgal/src/Core/controller/stage/pixi/PixiController.ts
packages/webgal/src/Stage/MainStage/useSetBg.ts

feat: Spine background

---

packages/webgal/src/translations/jp.ts

I fixed the Japanese dictionary to improve translations.
These changes should result in more natural-sounding translations for most Japanese users.

fix: improve Japanese translations

---

packages/webgal/src/Core/controller/gamePlay/backToTitle.ts
packages/webgal/src/Core/util/syncWithEditor/webSocketFunc.ts
packages/webgal/src/types/debugProtocol.ts
packages/webgal/vite.config.ts

For issue
模板预览用的游戏，用选项来选择，允许展示任何可能的游戏内界面 #309

feat: returnToTitle and executeCommand ws command

---

packages/webgal/src/Core/controller/stage/pixi/PixiController.ts
packages/webgal/src/Stage/MainStage/useSetFigure.ts

fix: handle spine with .json, fix spine pivot problem

---

packages/webgal/src/translations/zh-tw.ts

- Update translations and fix typos for better localization

feat: Update translations and fix typos for better localization

---

packages/webgal/src/UI/Menu/Options/OptionInterface.ts
packages/webgal/src/UI/Menu/Options/OptionSlider.tsx
packages/webgal/src/UI/Menu/Options/slider.css

- 为滑块组件添加动态数值提示气泡
- 支持悬停/拖拽时显示当前值
- 气泡跟随滑块精确移动
Resolves: #620

feat(slider): Add dynamic value tooltip with hover/drag interaction

---

packages/webgal/src/Core/util/syncWithEditor/webSocketFunc.ts
packages/webgal/src/Stage/TextBox/TextBox.tsx
packages/webgal/src/store/GUIReducer.ts
packages/webgal/src/store/guiInterface.ts
packages/webgal/src/types/debugProtocol.ts

字体优化默认关闭，当编辑器发送 `FONT_OPTIMIZATION ` 指令时开启

feat: add debug command `FONT_OPTIMIZATION`

---

packages/webgal/package.json
packages/webgal/src/Core/initializeScript.ts
packages/webgal/src/config/info.ts
packages/webgal/src/vite-env.d.ts
packages/webgal/vite.config.ts
yarn.lock

like https://github.com/OpenWebGAL/WebGAL_Terre/pull/383

feat: Automatically inject build information

---

packages/webgal/src/Core/controller/stage/pixi/PixiController.ts

fix: correct pivot point and positioning for Live2D figure

---

packages/webgal/public/game/scene/demo_zh_cn.txt
packages/webgal/src/Core/gameScripts/getUserInput/index.tsx

当不输入任何值时，则使用 `-defaultValue=xxx` 的值（如果存在的话）
issue: #668

feat: getUserinput add default value
